# =========================================
#  Configuración de SharedFate
#  Después de cambiar algo aquí, usa /sharedfate reload
#  (o reinicia el servidor) para aplicar los cambios.
# =========================================
shared-health:
  enabled: true
shared-hunger:
  enabled: true
shared-mining:
  enabled: true
  broadcast: true
  materials:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - NETHER_GOLD_ORE
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - COAL_ORE
    - DEEPSLATE_COAL_ORE
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - STONE
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - MANGROVE_LOG
    - CHERRY_LOG
    - PALE_OAK_LOG
    - CRIMSON_STEM
    - WARPED_STEM
    - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_ACACIA_LOG
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_MANGROVE_LOG
    - STRIPPED_CHERRY_LOG
    - STRIPPED_PALE_OAK_LOG
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_WARPED_STEM
    - WHEAT
    - CARROTS
    - POTATOES
    - BEETROOTS
    - MELON
    - PUMPKIN
    - SWEET_BERRY_BUSH
    - COCOA
    - CAVE_VINES
    - CAVE_VINES_PLANT
